# Generated by Django 5.0.1 on 2024-01-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacobuilt_backend', '0002_add_default_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp']},
        ),
    ]
